import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import { AuthProvider } from "@/context/AuthContext";
import { SocketProvider } from "@/socket/socket";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<AuthProvider>
			<SocketProvider>
				<html lang="en">
					<body className={`${inter.className}`}>
						<Navbar />
						{children}
					</body>
				</html>
			</SocketProvider>
		</AuthProvider>
	);
}
