import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import { AuthProvider } from "@/context/authContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<AuthProvider>
			<html lang="en">
				<body className={`${inter.className}`}>
					<Navbar />
					{children}
				</body>
			</html>
		</AuthProvider>
	);
}
